# Generated by Django 4.2.7 on 2023-12-21 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distributor', '0006_distributor_weekly_schedule'),
        ('restaurant', '0004_restaurant_weekly_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('out_of_stock', models.BooleanField(default=False)),
                ('distributor_notes', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_minutes', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_restaurant', 'Pending Restaurant Approval'), ('approved', 'Approved'), ('rejected_by_restaurant', 'Rejected By Restaurant'), ('archived', 'Archived')], default='draft', max_length=30)),
                ('paused', models.BooleanField(default=False)),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distributor.distributor')),
            ],
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('matched', 'Matched'), ('pending_distributor', 'Pending Distributor Approval'), ('pending_restaurant', 'Pending Restaurant Approval'), ('approved', 'Approved'), ('rejected_by_distributor', 'Rejected By Distributor'), ('rejected_by_restaurant', 'Rejected By Restaurant')], default='matched', max_length=30)),
                ('locomotion', models.CharField(choices=[('walking', 'Walk'), ('bicycling', 'Bicycle'), ('driving', 'Car')], max_length=20)),
                ('minutes_distance', models.IntegerField()),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distributor.distributor')),
                ('menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.menu')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItemCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.menuitemcategory')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('overridden_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('percentage_adjustment', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('dollar_adjustment', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.item')),
                ('parent_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.menu')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_items',
            field=models.ManyToManyField(to='partners.menuitem'),
        ),
        migrations.AddField(
            model_name='menu',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant'),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.menuitemcategory'),
        ),
        migrations.AddField(
            model_name='item',
            name='distributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distributor.distributor'),
        ),
        migrations.AddConstraint(
            model_name='partners',
            constraint=models.CheckConstraint(check=models.Q(('minutes_distance__gt', 0)), name='partner_minutes_distance_positive_constraint'),
        ),
        migrations.AlterUniqueTogether(
            name='partners',
            unique_together={('distributor', 'restaurant')},
        ),
        migrations.AlterUniqueTogether(
            name='menuitem',
            unique_together={('parent_menu', 'item')},
        ),
        migrations.AddConstraint(
            model_name='menu',
            constraint=models.CheckConstraint(check=models.Q(('delivery_minutes__gt', 0), ('delivery_minutes__isnull', True), _connector='OR'), name='menu_delivery_minutes_positive_constraint'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.CheckConstraint(check=models.Q(('price__gt', 0)), name='menu_item_price_positive_constraint'),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('distributor', 'name')},
        ),
    ]
