# Generated by Django 4.2.7 on 2023-11-29 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0003_restaurant_minutes_distance_and_more'),
        ('distributor', '0004_distributor_minutes_distance_positive_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('matched', 'Matched'), ('pending_distributor', 'Pending Distributor Approval'), ('pending_restaurant', 'Pending Restaurant Approval'), ('approved', 'Approved'), ('rejected_by_distributor', 'Rejected By Distributor'), ('rejected_by_restaurant', 'Rejected By Restaurant')], max_length=30)),
                ('locomotion', models.CharField(choices=[('walk', 'Walk'), ('bike', 'Bicycle'), ('car', 'Car')], max_length=20)),
                ('minutes_distance', models.IntegerField()),
                ('distributor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='distributor.distributor')),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
            ],
        ),
        migrations.AddConstraint(
            model_name='partners',
            constraint=models.CheckConstraint(check=models.Q(('minutes_distance__gt', 0)), name='partner_minutes_distance_positive_constraint'),
        ),
    ]
