# Generated by Django 4.2.7 on 2023-11-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners',
            name='status',
            field=models.CharField(choices=[('matched', 'Matched'), ('pending_distributor', 'Pending Distributor Approval'), ('pending_restaurant', 'Pending Restaurant Approval'), ('approved', 'Approved'), ('rejected_by_distributor', 'Rejected By Distributor'), ('rejected_by_restaurant', 'Rejected By Restaurant')], default='matched', max_length=30),
        ),
    ]
