# Generated by Django 4.2.7 on 2023-12-21 22:35

from django.db import migrations

from partners.models import MenuItemCategory


def load_initial_data(apps, schema_editor):
    beverage = MenuItemCategory.objects.create(name='Beverage', description='Any beverage')
    wine = MenuItemCategory.objects.create(name='Wine', description='Any Wine', parent_category=beverage)
    red_wine = MenuItemCategory.objects.create(name='Red Wine', description='Any Red Wine', parent_category=wine)
    white_wine = MenuItemCategory.objects.create(name='White Wine', description='Any White Wine', parent_category=wine)
    rose_wine = MenuItemCategory.objects.create(name='Rose Wine', description='Any Rose Wine', parent_category=wine)
    sparkling_wine = MenuItemCategory.objects.create(name='Sparkling Wine', description='Any Sparkling Wine',
                                                     parent_category=wine)
    beer = MenuItemCategory.objects.create(name='Beer', description='Any beer')


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_alter_menu_status_alter_partners_status'),
    ]

    operations = [
        migrations.RunPython(load_initial_data),
    ]