# Generated by Django 4.2.7 on 2023-11-30 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_restaurant_minutes_distance_and_more'),
        ('distributor', '0005_alter_distributor_locomotion'),
        ('partners', '0003_alter_partners_locomotion_alter_partners_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners',
            name='distributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distributor.distributor'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='status',
            field=models.CharField(choices=[('matched', 'Matched'), ('pending_distributor', 'Pending Distributor Approval'), ('pending_restaurant', 'Pending Restaurant Approval'), ('approved', 'Approved'), ('rejected_by_distributor', 'Rejected By Distributor'), ('rejected_by_restaurant', 'Rejected By Restaurant')], default='matched', max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='partners',
            unique_together={('distributor', 'restaurant')},
        ),
    ]
