# Generated by Django 4.2.7 on 2023-12-01 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_restaurant_minutes_distance_and_more'),
        ('distributor', '0005_alter_distributor_locomotion'),
        ('partners', '0004_alter_partners_distributor_alter_partners_restaurant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('delivery_minutes', models.IntegerField()),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distributor.distributor')),
            ],
        ),
        migrations.AlterField(
            model_name='partners',
            name='status',
            field=models.CharField(choices=[('matched', 'Matched'), ('pending_distributor', 'Pending Distributor Approval'), ('pending_restaurant', 'Pending Restaurant Approval'), ('approved', 'Approved'), ('rejected_by_distributor', 'Rejected By Distributor'), ('rejected_by_restaurant', 'Rejected By Restaurant')], default='matched', max_length=30),
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('parent_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.menu')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_items',
            field=models.ManyToManyField(to='partners.menuitem'),
        ),
        migrations.AddField(
            model_name='menu',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant'),
        ),
        migrations.AddConstraint(
            model_name='menuitem',
            constraint=models.CheckConstraint(check=models.Q(('price__gt', 0)), name='menu_item_price_positive_constraint'),
        ),
        migrations.AlterUniqueTogether(
            name='menuitem',
            unique_together={('parent_menu', 'name')},
        ),
        migrations.AddConstraint(
            model_name='menu',
            constraint=models.CheckConstraint(check=models.Q(('delivery_minutes__gt', 0)), name='menu_delivery_minutes_positive_constraint'),
        ),
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together={('distributor', 'restaurant')},
        ),
    ]
