# Generated by Django 4.2.7 on 2023-12-01 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0005_alter_distributor_locomotion'),
        ('restaurant', '0003_restaurant_minutes_distance_and_more'),
        ('partners', '0005_menu_alter_partners_status_menuitem_menu_menu_items_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='menu',
            name='status',
            field=models.CharField(choices=[('matched', 'Draft'), ('pending_restaurant', 'Pending Restaurant Approval'), ('approved', 'Approved'), ('rejected_by_restaurant', 'Rejected By Restaurant'), ('archived', 'Archived')], default='matched', max_length=30),
        ),
        migrations.AddField(
            model_name='menu',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='partners',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.menu'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='status',
            field=models.CharField(choices=[('matched', 'Matched'), ('pending_distributor', 'Pending Distributor Approval'), ('pending_restaurant', 'Pending Restaurant Approval'), ('approved', 'Approved'), ('rejected_by_distributor', 'Rejected By Distributor'), ('rejected_by_restaurant', 'Rejected By Restaurant')], default='matched', max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together={('distributor', 'restaurant', 'version')},
        ),
    ]
