# Generated by Django 4.2.7 on 2023-12-03 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0010_alter_menu_status_alter_partners_status'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='menu',
            name='menu_delivery_minutes_positive_constraint',
        ),
        migrations.AlterField(
            model_name='menu',
            name='delivery_minutes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_restaurant', 'Pending Restaurant Approval'), ('approved', 'Approved'), ('rejected_by_restaurant', 'Rejected By Restaurant'), ('archived', 'Archived')], default='draft', max_length=30),
        ),
        migrations.AlterField(
            model_name='partners',
            name='status',
            field=models.CharField(choices=[('matched', 'Matched'), ('pending_distributor', 'Pending Distributor Approval'), ('pending_restaurant', 'Pending Restaurant Approval'), ('approved', 'Approved'), ('rejected_by_distributor', 'Rejected By Distributor'), ('rejected_by_restaurant', 'Rejected By Restaurant')], default='matched', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='menu',
            constraint=models.CheckConstraint(check=models.Q(('delivery_minutes__gt', 0), ('delivery_minutes__isnull', True), _connector='OR'), name='menu_delivery_minutes_positive_constraint'),
        ),
    ]
