# Generated by Django 4.2.7 on 2024-02-19 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0008_alter_menu_status_alter_partners_status'),
        ('restaurant', '0004_restaurant_weekly_schedule'),
        ('customer', '0003_customer_created_at_customer_email_customer_verified'),
        ('distributor', '0006_distributor_weekly_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_status', models.CharField(max_length=100, null=True)),
                ('restaurant_additional_info', models.TextField(null=True)),
                ('customer_notes', models.TextField(null=True)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('distributor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='distributor.distributor')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.customerorder')),
            ],
        ),
        migrations.AddField(
            model_name='customerorder',
            name='items',
            field=models.ManyToManyField(through='cart.OrderItem', to='partners.item'),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.menu'),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant'),
        ),
    ]
