# Generated by Django 4.2.6 on 2023-11-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottleserviceuser',
            name='account_type',
            field=models.CharField(choices=[('distributor', 'DISTRIBUTOR'), ('restaurant', 'RESTAURANT'), ('customer', 'CUSTOMER'), ('admin', 'ADMIN')], max_length=50),
        ),
    ]
