# Generated by Django 4.2.6 on 2023-11-05 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('distributor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributor',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='location.address'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
