# Generated by Django 4.2.7 on 2023-11-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0002_alter_distributor_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor',
            name='locomotion',
            field=models.CharField(choices=[('walk', 'Walk'), ('bike', 'Bicycle'), ('car', 'Car')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='distributor',
            name='minutes_distance',
            field=models.IntegerField(null=True),
        ),
    ]
