# Generated by Django 4.2.7 on 2023-11-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0003_distributor_locomotion_distributor_minutes_distance'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='distributor',
            constraint=models.CheckConstraint(check=models.Q(('minutes_distance__gt', 0), ('minutes_distance__isnull', True), _connector='OR'), name='minutes_distance_positive_constraint'),
        ),
    ]
