# Generated by Django 4.2.7 on 2023-11-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_restaurant_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='minutes_distance',
            field=models.IntegerField(null=True),
        ),
        migrations.AddConstraint(
            model_name='restaurant',
            constraint=models.CheckConstraint(check=models.Q(('minutes_distance__gt', 0), ('minutes_distance__isnull', True), _connector='OR'), name='restaurant_minutes_distance_positive_constraint'),
        ),
    ]
