# Generated by Django 4.2.7 on 2023-12-03 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
        ('restaurant', '0003_restaurant_minutes_distance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='weekly_schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.weeklyschedule'),
        ),
    ]
